# Configuracion de Resilience4j
resilience4j.circuitbreaker:
  instances:
    customerServiceCB: # Nombre de la instancia del Circuit Breaker
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.timelimiter:
  instances:
    customerServiceCB: # Debe coincidir con el nombre de la instancia del Circuit Breaker
      timeout-duration: 2s
      cancel-running-future: true
